project:
  type: website

website:
  title: "Justin's Blog"
  site-url: "https://blog.jwong.dev"
  description: "Academic papers, Data Science, and Software Engineering."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
  page-footer:
    center: |
      © {{< meta year >}} Justin JH Wong

format:
  html:
    theme:
      light: zephyr
      dark: lux
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    number-sections: false

metadata-files:
  - _metadata.yml