project:
  type: website

website:
  title: "Justin's Blog"
  site-url: "https://blog.jwong.dev"
  description: "Academic papers, Data Science, and Software Engineering."
  navbar:
    left:
      - text: Home
        href: index.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/amidstdebug/
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=SRBrkisAAAAJ&hl=en
      - icon: youtube
        href: https://www.youtube.com/@justinjhwong
  page-footer:
    center: |
      © {{< meta year >}} Justin JH Wong

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    number-sections: false
    filters:
      - fancy-text
      - fontawesome
      - lightbox

metadata-files:
  - _metadata.yml
